#!/usr/bin/env bash
set -o pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CONF="${HERE}/sources.conf"

die() { echo "refresh: ERROR: $*" >&2; exit 1; }
note() { echo "refresh: $*"; }

[ -f "${CONF}" ] || die "no sources.conf at ${CONF}"

slug_from_subject() {
    echo "$1" \
        | sed -e 's/^Subject: //' -e 's/^\[PATCH[^]]*\] //' \
        | tr 'A-Z' 'a-z' \
        | sed -e 's/[^a-z0-9]\+/-/g' -e 's/^-//' -e 's/-$//' \
        | cut -c1-60
}

disabled_slugs() {
    local series_file="$1"
    [ -f "${series_file}" ] || return 0
    grep -E '^\s*#' "${series_file}" 2>/dev/null \
        | sed -e 's/^\s*#\s*//' -e 's/\.patch$//' -e 's/^[0-9]\{4\}-//' || true
}

local_series_entries() {
    local series_file="$1"
    [ -f "${series_file}" ] || return 0
    grep -E '^\s*#?\s*[^[:space:]#]+\.patch\s*$' "${series_file}" 2>/dev/null \
        | grep -vE '^\s*#?\s*[0-9]{4}-' \
        | sed -e 's/^[[:space:]]*//' -e 's/[[:space:]]*$//' || true
}

entry_filename() {
    echo "$1" | sed -e 's/^#[[:space:]]*//' -e 's/^[[:space:]]*//' -e 's/[[:space:]]*$//'
}

refresh_series() {
    local series="$1"; shift
    local -a urls=("$@")
    local dir="${HERE}/${series}"
    local tmp
    tmp="$(mktemp -d)"
    trap 'rm -rf "${tmp}"' RETURN

    local u i=0
    : > "${tmp}/combined.patch"
    for u in "${urls[@]}"; do
        i=$((i + 1))
        note "fetching ${series} source ${i}/${#urls[@]}: ${u}"
        if ! curl -fsSL "${u}" -o "${tmp}/src-${i}.patch"; then
            echo "refresh: ${series}: download failed for ${u}" >&2
            return 1
        fi
        [ -s "${tmp}/src-${i}.patch" ] || { echo "refresh: ${series}: empty response for ${u}" >&2; return 1; }
        grep -q '^From [0-9a-f]\{40\} ' "${tmp}/src-${i}.patch" \
            || { echo "refresh: ${series}: not a format-patch mbox: ${u}" >&2; return 1; }
        cat "${tmp}/src-${i}.patch" >> "${tmp}/combined.patch"
    done

    local -a disabled
    mapfile -t disabled < <(disabled_slugs "${dir}/series")

    local -a local_entries
    mapfile -t local_entries < <(local_series_entries "${dir}/series")

    mkdir -p "${dir}"
    rm -f "${dir}"/[0-9][0-9][0-9][0-9]-*.patch

    awk -v out="${tmp}" '
        /^From [0-9a-f]{40} / { n++ }
        n > 0 { printf "%s", $0 "\n" > sprintf("%s/part-%04d", out, n) }
    ' "${tmp}/combined.patch"

    local part idx=0 slug target
    : > "${tmp}/series.new"
    for part in "${tmp}"/part-*; do
        idx=$((idx + 1))
        slug="$(slug_from_subject "$(grep -m1 '^Subject:' "${part}")")"
        [ -n "${slug}" ] || slug="patch"
        target="$(printf '%04d-%s.patch' "${idx}" "${slug}")"
        cp "${part}" "${dir}/${target}"

        local is_disabled=0 d
        for d in "${disabled[@]:-}"; do
            [ -n "${d}" ] && [ "${d}" = "${slug}" ] && is_disabled=1
        done
        if [ "${is_disabled}" = 1 ]; then
            echo "# ${target}" >> "${tmp}/series.new"
            note "  ${target} (kept disabled)"
        else
            echo "${target}" >> "${tmp}/series.new"
        fi
    done

    {
        echo "# Entries named NNNN-*.patch are generated by refresh.sh from the"
        echo "# sources in sources.conf and are rewritten on every refresh."
        echo "# Any other entry is yours: refresh.sh preserves it and never"
        echo "# touches the file. Comment a line out to retire that patch;"
        echo "# commented-out entries stay commented out across refreshes."
        cat "${tmp}/series.new"
        local le lf kept=0
        for le in "${local_entries[@]:-}"; do
            [ -n "${le}" ] || continue
            lf=$(entry_filename "${le}")
            if [ -f "${dir}/${lf}" ]; then
                echo "${le}"
                kept=$((kept + 1))
            else
                echo "refresh: WARNING: ${series}/series lists ${lf} but the file is missing; dropped" >&2
            fi
        done
        [ "${kept}" -gt 0 ] && echo "refresh:   preserved ${kept} local patch entry(ies)" >&2
    } > "${dir}/series"

    {
        echo "fetched_at: $(date -u +%Y-%m-%dT%H:%M:%SZ)"
        echo "sources:"
        i=0
        for u in "${urls[@]}"; do
            i=$((i + 1))
            echo "  - url: ${u}"
            echo "    sha256: $(sha256sum "${tmp}/src-${i}.patch" | awk '{print $1}')"
            echo "    commits: $(grep -c '^From [0-9a-f]\{40\} ' "${tmp}/src-${i}.patch")"
        done
        echo "combined_sha256: $(sha256sum "${tmp}/combined.patch" | awk '{print $1}')"
        echo "generated_patches:"
        local f
        for f in "${dir}"/[0-9][0-9][0-9][0-9]-*.patch; do
            echo "  $(basename "${f}")  $(sha256sum "${f}" | awk '{print $1}')"
        done
    } > "${dir}/PROVENANCE"

    note "${series}: ${idx} patch(es) from ${#urls[@]} source(s) written to ${dir}"
    return 0
}

rc=0
want=("$@")

declare -a all_series=()
while read -r series url; do
    case "${series}" in ''|\#*) continue ;; esac
    [ -n "${url}" ] || continue
    seen=0
    for existing in "${all_series[@]:-}"; do
        [ "${existing}" = "${series}" ] && seen=1
    done
    [ "${seen}" = 0 ] && all_series+=("${series}")
done < "${CONF}"

for series in "${all_series[@]:-}"; do
    [ -n "${series}" ] || continue
    if [ ${#want[@]} -gt 0 ]; then
        found=0
        for w in "${want[@]}"; do [ "${w}" = "${series}" ] && found=1; done
        [ "${found}" = 1 ] || continue
    fi

    declare -a urls=()
    while read -r s_name s_url; do
        case "${s_name}" in ''|\#*) continue ;; esac
        [ "${s_name}" = "${series}" ] || continue
        [ -n "${s_url}" ] && urls+=("${s_url}")
    done < "${CONF}"

    if ! refresh_series "${series}" "${urls[@]}"; then
        echo "refresh: WARNING: could not refresh ${series}" >&2
        if [ -f "${HERE}/${series}/series" ]; then
            echo "refresh: keeping existing checked-in series for ${series}" >&2
        else
            echo "refresh: and there is no checked-in series to fall back to" >&2
            rc=1
        fi
    fi
done

exit $rc
